apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: keetu0uym-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/keetu0uym-dotnet-basic-gitops